# Generated by Django 5.2.4 on 2025-08-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mobile', 'Mobile Update'), ('demographics', 'Demographics'), ('child', 'Child Enrollment'), ('aadhaarno', 'Aadhaar Number'), ('aadhaarpdf', 'Aadhaar PDF')], max_length=20)),
                ('data', models.JSONField()),
                ('fingerprints', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('birthCertificate', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('childPhoto', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('addressProof', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
