# Generated by Django 5.2.4 on 2025-08-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='addressProof',
        ),
        migrations.RemoveField(
            model_name='order',
            name='birthCertificate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='childPhoto',
        ),
        migrations.RemoveField(
            model_name='order',
            name='data',
        ),
        migrations.RemoveField(
            model_name='order',
            name='document',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
        migrations.AddField(
            model_name='order',
            name='aadhaar_number',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='father_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('mobile', 'Mobile Update'), ('child', 'Child Enrollment'), ('demographics', 'Demographics'), ('aadharno', 'Aadhaar Number'), ('aadharpdf', 'Aadhaar PDF')], default='mobile', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='purpose',
            field=models.CharField(choices=[('Mobile Number Update', 'Mobile Number Update'), ('Email Id Update', 'Email Id Update'), ('Email Id & Mobile Update', 'Email Id & Mobile Update')], default='Mobile Number Update', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='fingerprints',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
