# Generated by Django 5.2.4 on 2025-08-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_order_addressproof_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='aadhaar_number',
            new_name='aadhaarNumber',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='father_name',
            new_name='fatherName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='mobile_number',
            new_name='mobileNumber',
        ),
    ]
