# Generated by Django 5.2.4 on 2025-08-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_aadhaar_number_order_aadhaarnumber_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
