# Generated by Django 5.2.4 on 2025-08-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='file',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='order',
            name='aadhaarNumber',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='fatherName',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fingerprints',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='formData',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='fullName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='mobileNumber',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='orderType',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('child', 'Child'), ('demographics', 'Demographics')], default='mobile', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='uploadedFiles',
            field=models.JSONField(default=dict),
        ),
    ]
