# Generated by Django 5.2.4 on 2025-08-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_order_address_remove_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fatherName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
