# Generated by Django 5.2.4 on 2025-08-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='aadhaarNumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fatherName',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mobileNumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='uploadedFiles',
        ),
    ]
