# Generated by Django 5.2.4 on 2025-08-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_order_aadhaarnumber_remove_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fullName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
