# Generated by Django 5.2.4 on 2025-08-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='aadhaarNumber',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='fatherName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='mobileNumber',
            field=models.CharField(default='', max_length=15),
        ),
    ]
