# Generated by Django 5.2.4 on 2025-08-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_aadhaarnumber_order_email_order_fathername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='male', max_length=50),
        ),
    ]
