# Generated by Django 5.2.4 on 2025-08-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fatherAadhaarNumber',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='fatherName',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='fullName',
            field=models.CharField(default='', max_length=30),
        ),
    ]
